services:
  database:
    image: mysql:8.0.36
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: devotion
      MYSQL_DATABASE: coop-bank
    ports:
      - 3308:3306
    expose:
      - 3306
  server:
    build:
      context: ./coop-server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: database
      DB_PORT: 3306
    ports:
      - 3001:3001
    expose:
      - 3001
    depends_on:
      - database
  client:
    build:
      context: ./coop-client
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - server


# docker compose up -d