### get all branchs
GET http://localhost:3000/branch

### create a new branch
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "hieuthang@gmail.com",
    "password": "1231299",
    "username": "10001"
}

### get detail branch
GET http://localhost:3000/branch/140