const DATE_FORMAT_DDMMYYYY = 'DD/MM/YYYY';
const DATE_FORMAT_YYYYMMDDHHMMSS = 'YYYY-MM-DD HH:mm:ss';
const DATE_TIME_FORMAT = 'HH:MM DD/MM/YYYY';

export { DATE_FORMAT_DDMMYYYY, DATE_TIME_FORMAT, DATE_FORMAT_YYYYMMDDHHMMSS };
