import { Injectable } from '@nestjs/common';

@Injectable()
export class MenuService {
  findAll() {
    return [
      {
        menu_id: '1',
        menu_name: 'BÁO CÁO',
        module_id: null,
        module_name: null,
        link_menu: '/',
        icon_path: 'fi fi-rr-display-code',
        parent_id: '0',
        is_active: 1,
        is_system: 0,
        is_business: 0,
        order_index: '0',
        description: null,
        function_name: null
      },
      {
        menu_id: '10',
        menu_name: 'NGƯỜI ĐẠI DIỆN',
        module_id: null,
        module_name: null,
        link_menu: '/representative',
        icon_path: 'fi fi-rr-user-add',
        parent_id: '0',
        is_active: 1,
        is_system: 0,
        is_business: 0,
        order_index: '11',
        description: null,
        function_name: null
      },
      {
        menu_id: '3',
        menu_name: 'ĐƠN VỊ LIÊN KẾT',
        module_id: null,
        module_name: null,
        link_menu: '/affiliate-unit',
        icon_path: 'fi fi-rr-users',
        parent_id: '0',
        is_active: 1,
        is_system: 0,
        is_business: 0,
        order_index: '7',
        description: null,
        function_name: null
      },
      {
        menu_id: '4',
        menu_name: 'CÁ NHÂN VAY VỐN',
        module_id: null,
        module_name: null,
        link_menu: '/individual',
        icon_path: 'fi fi-rr-user',
        parent_id: '0',
        is_active: 1,
        is_system: 0,
        is_business: 0,
        order_index: '7',
        description: null,
        function_name: null
      },
      {
        menu_id: '20',
        menu_name: 'CHĂM SÓC KH',
        module_id: null,
        module_name: null,
        link_menu: '/customer-care',
        icon_path: 'fi fi-rr-gift',
        parent_id: '0',
        is_active: 1,
        is_system: 0,
        is_business: 0,
        order_index: '7',
        description: null,
        function_name: null
      },
      {
        menu_id: '21',
        menu_name: 'Quà tặng',
        module_id: null,
        module_name: null,
        link_menu: '/gift',
        parent_id: '20',
        is_active: 1,
        is_system: 0,
        is_business: 0,
        order_index: '7',
        description: null,
        function_name: null
      },
      {
        menu_id: '22',
        menu_name: 'Ngày đặc biệt',
        module_id: null,
        module_name: null,
        link_menu: '/special-day',
        parent_id: '20',
        is_active: 1,
        is_system: 0,
        is_business: 0,
        order_index: '7',
        description: null,
        function_name: null
      },
      {
        menu_id: '5',
        menu_name: 'HỆ THỐNG',
        module_id: null,
        module_name: null,
        link_menu: '#',
        icon_path: 'fi fi-rr-settings',
        parent_id: '0',
        is_active: 1,
        is_system: 0,
        is_business: 0,
        order_index: '100',
        description: null,
        function_name: null
      },
      {
        menu_id: '2',
        menu_name: 'Chi nhánh',
        module_id: null,
        module_name: null,
        link_menu: '/branch',
        parent_id: '5',
        is_active: 1,
        is_system: 0,
        is_business: 0,
        order_index: '10',
        description: null,
        function_name: null
      },
      {
        menu_id: '7',
        menu_name: 'Đại diện',
        module_id: null,
        module_name: null,
        link_menu: '/bank-representative',
        parent_id: '5',
        is_active: 1,
        is_system: 0,
        is_business: 0,
        order_index: '11',
        description: null,
        function_name: null
      },
      {
        menu_id: '6',
        menu_name: 'Nhân viên',
        module_id: null,
        module_name: null,
        link_menu: '/user',
        parent_id: '5',
        is_active: 1,
        is_system: 0,
        is_business: 0,
        order_index: '11',
        description: null,
        function_name: null
      }
    ];
  }
}
